### ISSUE TITLE
Esp8266

### ISSUE THREAD

**Issue by Bye0786** [Mazuk/MazukClock#2]
Hallo, geht das Sketch auf einen Wemos D1 mini?
bekomme irgendwie immer Fehler beim Komplimieren

C:\Users\Acer 8946\Documents\Arduino\libraries\FastLED\src/fastspi.h:135:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  135 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

**Comment by Mazuk** [comment]
Hi 
Was für ein Fehler?
Sollte auch auf einem Wemos D1 Mini gehen.
Alle Bibliotheken geladen?

Von meinem iPhone gesendet

**Comment by Bye0786** [comment]
Ich bekomme immer diese Pragma Meldungen, aber irgendwie habe ich paar mal die Alte Version von Panbachi geflast und dann die 2.80 irgendwie hat er es jetzt wieder angenommen, keine Ahnung woran das liegt der lag!?
Was mir noch grade auffällt ich sitze grade vor der Uhr 
Sie zeigt Zwanzig vor Elf und "Z" von Zehn leuchtet zusätzlich, dann ist die Uhr auf Viertel vor Elf umgesprungen aber "Z" von Zehn in Zeile 2 Leuchtet trotzdem.
habe folgende Einstellungen
Grid First 3
und das 10 x11
Gruß Bye0786

**Comment by Mazuk** [comment]
Steht das Z immer? Hört sich mehr nach einem Problem mit deiner HW an.



Von: Bye0786
Gesendet: Samstag, 22. Mai 2021 10:49
An: Mazuk/MazukClock
Cc: Mazuk; Comment
Betreff: Re: [Mazuk/MazukClock] Esp8266 (#2)

Ich bekomme immer diese Pragma Meldungen, aber irgendwie habe ich paar mal die Alte Version von Panbachi geflast und dann die 2.80 irgendwie hat er es jetzt wieder angenommen, keine Ahnung woran das liegt der lag!?
Was mir noch grade auffällt ich sitze grade vor der Uhr
Sie zeigt Zwanzig vor Elf und "Z" von Zehn leuchtet zusätzlich, dann ist die Uhr auf Viertel vor Elf umgesprungen aber "Z" von Zehn in Zeile 2 Leuchtet trotzdem.
habe folgende Einstellungen
Grid First 3
und das 10 x11
Gruß Bye0786

**Comment by Bye0786** [comment]
Hi, es steht nicht immer. Nach dem es Zehn vor war geht es auch wieder weg. Habe mal Neu geflasht und den RTC mit dran gehangen. Mal Schauen wie es sich jetzt verhält.

**Comment by Bye0786** [comment]
Die Letzten 2 Tage konnte ich keine Auffälligkeiten erkennen. Die Uhr läuft Super.
Ich mache dann erstmal wieder zu.
Gruß
