### ISSUE TITLE
Läuft nicht nach selber kompilieren

### ISSUE THREAD

**Issue by Dirk1888** [Mazuk/MazukClock#3]
Hallo,
wenn ich die fertige bin aus der Zip Datei auf meinem Wemos D1 installiere läuft die Uhr,
beim selber kompilieren klappt auch alles aber der Wemos bootet nicht im Seriellen Monitor kommt nur folgendes,
kannst du mit der Ausgabe was anfangen.

21:23:22.317 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
21:23:22.317 -> 
21:23:22.317 -> load 0x4010f000, len 3584, room 16 
21:23:22.317 -> tail 0
21:23:22.317 -> chksum 0xb0
21:23:22.317 -> csum 0xb0
21:23:22.317 -> v2843a5ac
21:23:22.317 -> ~ld
21:23:24.051 -> 

Die Originale von panbachi läuft immer ohne Probleme

**Comment by Marcolist** [comment]
Gleiches Problem

**Comment by Mazuk** [comment]
Keine Ahnung warum es nicht geht. Gerade nochmals meine kompiliert ohne Probleme. Ich habe mal alles in ein zip file gepackt vielleicht geht es damit.
[wordclock_src2.83.zip](https://github.com/Mazuk/MazukClock/files/7460829/wordclock_src2.83.zip)
.

**Comment by Dirk1888** [comment]
Danke fürs testen, leider gehts mit dem zipfile auch nicht, gleicher Fehler.
Hab die Uhr ja 2 mal am laufen, aber ich kann den Fehler nicht ausmachen wieso das flashen manchmal geht und manchmal nicht.

**Comment by Mazuk** [comment]
Dann kann ich nur noch das Problem an den Einstellungen zum Board sehen.
Ich habe folgende:




Von: Dirk1888
Gesendet: Donnerstag, 4. November 2021 18:11
An: Mazuk/MazukClock
Cc: Mazuk; Comment
Betreff: Re: [Mazuk/MazukClock] Läuft nicht nach selber kompilieren (#3)

Danke fürs testen, leider gehts mit dem zipfile auch nicht, gleicher Fehler.
Hab die Uhr ja 2 mal am laufen, aber ich kann den Fehler nicht ausmachen wieso das flashen manchmal geht und manchmal nicht.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dirk1888** [comment]
> Dann kann ich nur noch das Problem an den Einstellungen zum Board sehen. Ich habe folgende: 

Seh ich die nicht oder gibts keine;)

**Comment by Timapheus** [comment]
> Hallo, wenn ich die fertige bin aus der Zip Datei auf meinem Wemos D1 installiere läuft die Uhr, beim selber kompilieren klappt auch alles aber der Wemos bootet nicht im Seriellen Monitor kommt nur folgendes, kannst du mit der Ausgabe was anfangen.
> 
> 21:23:22.317 -> ets Jan 8 2013,rst cause:2, boot mode:(3,6) 21:23:22.317 -> 21:23:22.317 -> load 0x4010f000, len 3584, room 16 21:23:22.317 -> tail 0 21:23:22.317 -> chksum 0xb0 21:23:22.317 -> csum 0xb0 21:23:22.317 -> v2843a5ac 21:23:22.317 -> ~ld 21:23:24.051 ->
> 
> Die Originale von panbachi läuft immer ohne Probleme

Habe leider den gleichen Fehler

**Comment by Mazuk** [comment]
Bitte nochmals probieren. Habe es bei mir mit einem neuen AZ-Delivery ESP8266 probiert und hatte auch einen Fehler. Failed to open Config file. Nach der schnellen Änderung in der config.cpp ging es.

**Comment by Timapheus** [comment]
Habe auch einen ganz neuen D1 Mini mit ESP8266-12F. Mit dem ursprünglichen Code läuft alles super. Bei der Version hier kriege ich immer die gleiche Ausgabe und die Uhr bootet nicht, Habe schon alles mögliche ausprobiert. Welche Änderung in der config.cpp ist gemeint? 
Vielen Dank

**Comment by Mazuk** [comment]
Diese hier
  File file = SPIFFS.open("/wordclock_config.json", "r");

  if(!file) {
    Serial.println("Failed to open config file. Will try to make");
    File file = SPIFFS.open("/wordclock_config.json", "w");

    if (!file) {
        Serial.println("Can't open wordclock_config.json for writing");
        //return;
    }
    Config::save();
    return;
  }else
     Serial.println("Load config.");



Von: Timapheus
Gesendet: Dienstag, 9. November 2021 15:22
An: Mazuk/MazukClock
Cc: Mazuk; Comment
Betreff: Re: [Mazuk/MazukClock] Läuft nicht nach selber kompilieren (#3)

Habe auch einen ganz neuen D1 Mini mit ESP8266-12F. Mit dem ursprünglichen Code läuft alles super. Bei der Version hier kriege ich immer die gleiche Ausgabe und die Uhr bootet nicht, Habe schon alles mögliche ausprobiert. Welche Änderung in der config.cpp ist gemeint?
Vielen Dank
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Timapheus** [comment]
Ändert leider auch nichts

**Comment by Mazuk** [comment]
Dann falsche libraries !?

**Comment by Timapheus** [comment]
Kann sein, kannst du vielleicht deine installierten libraries hier rein posten damit man abgleichen kann ob irgendeine Version etc. unterschiedlich sind?

**Comment by Mazuk** [comment]
Die Libraries und Versionen stehen alle in der readme

**Comment by Mazuk** [comment]
Hier noch meine Board Einstellungen
ESP8266 Sketch Data Upload
Board: "LOLIN(WEMOS) 01 R2 & mini"
Upload Speed: "921600"
CPU Frequency: "80 MHz"
Flash Size "4M8 (FS:2M8 OTA:-1019K8)"
Debug port: "Disabled"
Debug l ovel: "Keine"
lwlP Variant: "v2 l ower Memory"
VTables: "Flash"
Exceptions: "legacy (new can return nullptr)"
Erase Flash: "Only Sketch"
SSL Support ·All SSL cipheIS (most compatible)"
Port "COM3"

**Comment by Timapheus** [comment]
Okay es scheint jetzt zu funktionieren, es liegt glaube ich an der esp8266_mdns by mrdunk v1.1.7. Die schmeißt beim Kompilieren keine Fehler sorgt aber falls sie fehlt dafür das er nicht booten kann. 
Vielen Dank!

**Comment by Mazuk** [comment]
Freut mich wenn es jetzt geht. Viel Spass damit :-)

**Comment by Dirk1888** [comment]
Hab das in der config geändert, hat erstmal nichts gebracht,
dann hab ich Arduino und alle libs gelöscht und alles neu installiert und exakt darauf geachtet das die Versionen die angegeben sind installiert werden (waren vorher auch alle installiert nur ist da wohl was durcheinander gekommen)
jetzt läuft der Wemos nach dem flashen.
Vielen Dank nochmal

**Comment by Timapheus** [comment]
Bei mir hängt der Wemos sich nun in der Startsequenz auf und startet immer wieder neu, werde jetzt versuchen auch alles einmal zu löschen und nur genau die angegeben versionen zu installieren

**Comment by Timapheus** [comment]
Okay ich hab jetzt alle libs genauso wie in der Read.me. Wenn die Uhr neu startet hängt sie sich jedoch am Anfang bei der Regenborgen Animation auf und startet immer wieder neu. Nach ca. 25 Versuchen schafft sie es dann und die Uhrzeit wird angezeigt. Ich habe 10 Reihen und 11 Spalten, jedoch die LED's vertikal von oben links in der Ecke nach unten Links und dann wieder hoch verkabelt. 

Im Seriellen Monitor wird folgendes immer wieder ausgegeben
`Load config.
*WM: [1] AutoConnect 
*WM: [2] Connecting as wifi client... 
*WM: [3] STA static IP:
*WM: [2] setSTAConfig static ip not set, skipping 
*WM: [1] Connecting to SAVED AP: xxxxxxxxxxxxx
*WM: [3] Using Password: xxxxxxxxxxxxx
*WM: [3] WiFi station enable 
*WM: [3] enableSTA PERSISTENT ON 
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.0.25
mDNS responder started: wordclock
*WM: [3] unloading 
TCP server started

Couldn't find RTC

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffcb0 end: 3fffffc0 offset: 01a0
3ffffe50:  00000011 00000001 3fff5b00 3fff7a74  
3ffffe60:  11764137 ffffffff 3fff78ec 4023b7ee  
3ffffe70:  3fff5e80 00000000 00000000 00000063  
3ffffe80:  3ffffed2 00000002 3ffffec0 4020af5c  
3ffffe90:  3fff4bcf 0000007d 00000068 0a020202  
3ffffea0:  19190a0a 3fff0319 00000000 0000192f  
3ffffeb0:  00000019 0000007d 3fff4b64 4020b0e0  
3ffffec0:  3fff4b90 0000007d 0000007d 0a020202  
3ffffed0:  19190a0a 00000319 00000000 00000063  
3ffffee0:  00191919 4bc6a7f0 2c49ba5e 00000000  
3ffffef0:  19000000 3fff55d4 3fff4b64 40216be5  
3fffff00:  00191919 00000000 4010092c 00001945  
3fffff10:  4020b080 3fff4b90 0000007d 00000001  
3fffff20:  00000000 3fff5a00 0000012c 3fff58f4  
3fffff30:  001d37f9 3fff5a00 0000012c 0000121b  
3fffff40:  3fff4d07 3fff4b90 3fff55d4 4020110b  
3fffff50:  3fff4d07 3fff4b90 3fff55d4 40202ad1  
3fffff60:  000007cf 00000000 000e000f 80216ca5  
3fffff70:  3fff7880 7fa67999 3fff65f4 3fff58f4  
3fffff80:  00000000 00000033 3fff4a64 40202bb2  
3fffff90:  3fffdad0 00000000 3fff57a8 4020105d  
3fffffa0:  feefeffe feefeffe 3fff58b4 402201b8  
3fffffb0:  feefeffe feefeffe 3ffe9780 40101329  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld`


Weiß vielleicht jemand woran das liegen kann ?
